---
- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure /etc/containerd exists
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Check if containerd config exists
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  when: not containerd_config.stat.exists
  notify: restart containerd

- name: Enable SystemdCgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: restart containerd

- name: Ensure containerd is started and enabled
  systemd:
    name: containerd
    state: started
    enabled: yes
    daemon_reload: yes
